version: "3.8"

services:
  api_1:
    image: ghcr.io/miralriodev/arroyo-seco-api:latest
    restart: always
    ports:
      - "3001:3000"
    env_file: ./.env
  api_2:
    image: ghcr.io/miralriodev/arroyo-seco-api:latest
    restart: always
    ports:
      - "3002:3000"
    env_file: ./.env 
